# -*- coding: utf-8 -*-
"""Mini Project-1: Number Analyzer.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MHrtvlxBGR4Ej7-rfdxAZN6wFvdwEeW8

**Project Breakdown**

* Input: Integer n

* Tasks:

  * Check if n is even or odd

  * Check if n is a prime number

  * Find factorial of n
"""

def analyze_number(n):
    # Even or Odd
    if n % 2 == 0:
        print(f"{n} is Even")
    else:
        print(f"{n} is Odd")

    # Prime Check
    if n < 2:
        print(f"{n} is not a Prime Number")
    else:
        for i in range(2, int(n**0.5)+1):
            if n % i == 0:
                print(f"{n} is not a Prime Number")
                break
        else:
            print(f"{n} is a Prime Number")

    # Factorial
    factorial = 1
    for i in range(1, n+1):
        factorial *= i
    print(f"Factorial of {n} is {factorial}")

num = int(input("Enter a number: "))
analyze_number(num)